import { motion } from 'framer-motion';
import { TrendingUp, Briefcase, IndianRupee, Rocket, Zap, X } from 'lucide-react';

export function MarketIntelPanel({ data, onClose }) {
    if (!data) return null;

    const sections = [
        {
            title: 'Salary Range',
            icon: <IndianRupee size={16} />,
            content: [
                { label: 'Entry', value: data.salaryRange?.entry },
                { label: 'Mid', value: data.salaryRange?.mid },
                { label: 'Senior', value: data.salaryRange?.senior },
            ],
            color: 'bg-brutal-green'
        },
        {
            title: 'Market Demand',
            icon: <TrendingUp size={16} />,
            content: [{ label: 'Status', value: data.marketDemand }],
            color: 'bg-brutal-yellow'
        }
    ];

    return (
        <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="w-full bg-white border-4 border-black shadow-brutal p-6 mb-6 relative overflow-hidden"
        >
            <button
                onClick={onClose}
                className="absolute top-4 right-4 p-1 hover:bg-black hover:text-white border-2 border-transparent hover:border-black transition-colors"
            >
                <X size={20} />
            </button>

            <div className="flex items-center gap-3 mb-6">
                <div className="bg-black text-white p-2">
                    <Briefcase size={24} />
                </div>
                <h2 className="text-2xl font-black uppercase tracking-tight">Market Intelligence</h2>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                {/* Salary & Demand */}
                {sections.map((sec, i) => (
                    <div key={i} className="border-3 border-black p-4 space-y-3 bg-gray-50">
                        <div className="flex items-center gap-2 font-black uppercase text-xs text-gray-400">
                            {sec.icon} {sec.title}
                        </div>
                        <div className="space-y-2">
                            {sec.content.map((item, j) => (
                                <div key={j} className="flex justify-between items-center">
                                    <span className="font-mono text-[10px] text-gray-500 uppercase">{item.label}</span>
                                    <span className={`font-bold text-xs px-2 py-0.5 border-2 border-black ${sec.color}`}>
                                        {item.value}
                                    </span>
                                </div>
                            ))}
                        </div>
                    </div>
                ))}

                {/* Top Skills */}
                <div className="border-3 border-black p-4 bg-gray-50 lg:col-span-1">
                    <div className="flex items-center gap-2 font-black uppercase text-xs text-gray-400 mb-3">
                        <Zap size={16} /> Top Skills Required
                    </div>
                    <div className="flex flex-wrap gap-2">
                        {data.topSkills?.map((skill, i) => (
                            <span key={i} className="text-[10px] font-black uppercase bg-white border-2 border-black px-2 py-1 shadow-[2px_2px_0px_0px_#000]">
                                {skill}
                            </span>
                        ))}
                    </div>
                </div>

                {/* Growth */}
                <div className="border-3 border-black p-4 bg-black text-white lg:col-span-1">
                    <div className="flex items-center gap-2 font-black uppercase text-xs text-gray-400 mb-2">
                        <Rocket size={16} /> Growth Potential
                    </div>
                    <p className="text-[10px] font-mono leading-relaxed opacity-90 italic">
                        "{data.growthPotential}"
                    </p>
                </div>
            </div>

            <div className="mt-4 pt-4 border-t-2 border-dashed border-gray-200 flex items-center justify-between">
                <div className="flex items-center gap-3">
                    <span className="text-[10px] font-black uppercase text-gray-400">Target Companies:</span>
                    <div className="flex gap-2">
                        {data.hiringCompanies?.map((c, i) => (
                            <span key={i} className="text-[10px] font-bold underline decoration-brutal-blue decoration-2 underline-offset-2">{c}</span>
                        ))}
                    </div>
                </div>
                <span className="text-[8px] font-mono text-gray-300">DATA GENERATED BY AI MENTOR • REALTIME LOG</span>
            </div>
        </motion.div>
    );
}
